"""SQLite en local; PostgreSQL si DB_ENGINE=postgresql o DATABASE_URL es postgres://."""
from __future__ import annotations

import os
import re
import sqlite3
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any
from urllib.parse import unquote, urlparse

from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent / ".env")

DATA_DIR = Path(__file__).resolve().parent / ".data"
DB_PATH = DATA_DIR / "app.db"


def _engine() -> str:
    explicit = (os.environ.get("DB_ENGINE") or "").strip().lower()
    if explicit in ("sqlite", "sqlite3"):
        return "sqlite"
    if explicit in ("postgres", "postgresql", "psql"):
        return "postgresql"
    url = (os.environ.get("DATABASE_URL") or "").strip().lower()
    if url.startswith("postgres"):
        return "postgresql"
    return "sqlite"


def uses_postgres() -> bool:
    return _engine() == "postgresql"


def database_url() -> str:
    return (os.environ.get("DATABASE_URL") or "").strip()


class CompatRow(Mapping[str, Any]):
    """Fila con r['col'] y r[i] como sqlite3.Row."""

    def __init__(self, columns: Sequence[str], values: Sequence[Any]):
        self._columns = list(columns)
        self._values = list(values)
        self._map = {c: values[i] for i, c in enumerate(self._columns)}

    def __getitem__(self, key: str | int) -> Any:
        if isinstance(key, int):
            return self._values[key]
        return self._map[key]

    def __iter__(self):
        return iter(self._columns)

    def __len__(self) -> int:
        return len(self._columns)

    def keys(self):
        return list(self._columns)


class _Cursor:
    def __init__(self, rows: list[CompatRow], rowcount: int):
        self._rows = rows
        self.rowcount = rowcount
        self._i = 0

    def fetchone(self) -> CompatRow | None:
        if self._i >= len(self._rows):
            return None
        row = self._rows[self._i]
        self._i += 1
        return row

    def fetchall(self) -> list[CompatRow]:
        rest = self._rows[self._i :]
        self._i = len(self._rows)
        return rest


def _pragma_table_info_sql(table: str) -> tuple[str, str]:
    return (
        "SELECT ordinal_position - 1 AS cid, column_name AS name, data_type AS type, "
        "CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull, "
        "column_default AS dflt_value, 0 AS pk "
        "FROM information_schema.columns "
        "WHERE table_schema = current_schema() AND table_name = %s "
        "ORDER BY ordinal_position"
    ), table


def _rewrite_or_replace(sql: str) -> str:
    m = re.search(
        r"INSERT\s+OR\s+REPLACE\s+INTO\s+(\w+)\s*\(([^)]+)\)\s*VALUES\s*\(([^)]+)\)",
        sql,
        flags=re.I | re.S,
    )
    if not m:
        return sql
    table = m.group(1)
    cols = [c.strip() for c in m.group(2).split(",") if c.strip()]
    vals = m.group(3)
    if not cols:
        return sql
    pk = cols[0]
    updates = ", ".join(f"{c} = EXCLUDED.{c}" for c in cols[1:]) or f"{pk} = EXCLUDED.{pk}"
    return (
        f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({vals}) "
        f"ON CONFLICT ({pk}) DO UPDATE SET {updates}"
    )


def _qmarks_after_nocase(sql: str) -> str:
    sql = re.sub(
        r"([\w.]+)\s*=\s*\?\s*COLLATE\s+NOCASE",
        r"LOWER(\1) = LOWER(?)",
        sql,
        flags=re.I,
    )
    sql = re.sub(r"([\w.]+)\s+COLLATE\s+NOCASE", r"LOWER(\1)", sql, flags=re.I)
    return sql


def _adapt_sql(sql: str) -> str | tuple[str, str]:
    raw = sql.strip()
    pragma = re.match(r"PRAGMA\s+table_info\((\w+)\)\s*;?\s*$", raw, flags=re.I)
    if pragma:
        return ("__PRAGMA_TABLE_INFO__", pragma.group(1))
    if re.search(r"FROM\s+sqlite_master\s+WHERE\s+type\s*=\s*'table'", raw, flags=re.I):
        return (
            "SELECT table_name AS name FROM information_schema.tables "
            "WHERE table_schema = current_schema()"
        )
    sql = _rewrite_or_replace(sql)
    sql = re.sub(r"\s+COLLATE\s+NOCASE", "", sql, flags=re.I)
    sql = re.sub(r"\bBLOB\b", "BYTEA", sql, flags=re.I)
    sql = re.sub(
        r"INTEGER PRIMARY KEY AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        sql,
        flags=re.I,
    )
    sql = re.sub(
        r"username TEXT NOT NULL UNIQUE",
        "username TEXT NOT NULL",
        sql,
        flags=re.I,
    )
    sql = sql.replace("?", "%s")
    return sql


class PgConnection:
    def __init__(self, raw: Any):
        self._raw = raw

    def execute(self, sql: str, params: Sequence[Any] | None = None) -> _Cursor:
        import psycopg

        sql = _qmarks_after_nocase(sql)
        adapted = _adapt_sql(sql)
        try:
            if isinstance(adapted, tuple) and adapted[0] == "__PRAGMA_TABLE_INFO__":
                q, table = _pragma_table_info_sql(adapted[1])
                with self._raw.cursor() as cur:
                    cur.execute(q, (table,))
                    desc = [d.name for d in cur.description] if cur.description else []
                    rows = [CompatRow(desc, list(r)) for r in cur.fetchall()]
                    return _Cursor(rows, cur.rowcount)
            with self._raw.cursor() as cur:
                cur.execute(adapted, tuple(params) if params is not None else None)
                if cur.description:
                    desc = [d.name for d in cur.description]
                    rows = [CompatRow(desc, list(r)) for r in cur.fetchall()]
                else:
                    rows = []
                return _Cursor(rows, cur.rowcount if cur.rowcount is not None else 0)
        except psycopg.errors.UniqueViolation as e:
            raise sqlite3.IntegrityError(str(e)) from e
        except psycopg.Error as e:
            if "unique" in str(e).lower():
                raise sqlite3.IntegrityError(str(e)) from e
            raise

    def executemany(self, sql: str, seq: Sequence[Sequence[Any]]) -> _Cursor:
        sql = _qmarks_after_nocase(sql)
        adapted = _adapt_sql(sql)
        if isinstance(adapted, tuple):
            raise RuntimeError("executemany no admite PRAGMA")
        with self._raw.cursor() as cur:
            cur.executemany(adapted, list(seq))
            return _Cursor([], cur.rowcount if cur.rowcount is not None else 0)

    def executescript(self, sql: str) -> None:
        for part in sql.split(";"):
            stmt = part.strip()
            if stmt:
                self.execute(stmt)

    def commit(self) -> None:
        self._raw.commit()

    def close(self) -> None:
        self._raw.close()


def _connect_postgres() -> PgConnection:
    import psycopg

    url = database_url()
    if not url:
        raise RuntimeError("DB_ENGINE=postgresql requiere DATABASE_URL en el .env")
    raw = psycopg.connect(url)
    return PgConnection(raw)


def connect():
    if uses_postgres():
        return _connect_postgres()
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def ensure_postgres_extras(conn: Any) -> None:
    if not uses_postgres():
        return
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower ON users (LOWER(username))"
    )


def parse_database_url() -> dict[str, str]:
    url = database_url()
    if not url:
        return {}
    p = urlparse(url)
    return {
        "user": unquote(p.username or ""),
        "password": unquote(p.password or ""),
        "host": p.hostname or "127.0.0.1",
        "port": str(p.port or 5432),
        "dbname": (p.path or "").lstrip("/") or "pagina_monetizar",
    }
